# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Changed to NodePort for local access
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend